[package]
name = "thrum-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
strum_macros = "0.27.2"  # using EnumString for pretty_printing and FromRepr for OpCode conversions

[lib]
name = "thrum_engine"
path = "src/lib.rs"